
server:
  port: 8081

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        - id: common-ws
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1.0/flight/**

        - id: flight-ws
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/**

        - id: user-ws
          uri: http://localhost:8083
          predicates:
            - Path=/api/user/**

      discovery:
        enabled: true
        locator:
          enabled: true


  application:
    name: api-gateway

  boot:
    admin:
      client:
        url: "http://localhost:9090"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true